[package]
name = "rust-todo-frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { workspace = true }
dotenv = { workspace = true }
tokio = { workspace = true }
gloo = { workspace = true }