version: "3.8"

services:
  rust:
    container_name: rust_todo
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}
      - DISPLAY=$DISPLAY
      - WAYLAND_DISPLAY=$WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR=/tmp
      - PULSE_SERVER=$PULSE_SERVER
    build: .
    tty: true
    volumes:
      - .:/workspace
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: "${XDG_RUNTIME_DIR}/wayland-0"
        target: /tmp/wayland-0
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    networks:
      - rust_todo_net
  db:
    container_name: todo_db
    image: postgres:latest
    volumes: 
      - pgdata:/var/lib/postgresql/data
      - ./db_config/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256 --auth-local=scram-sha-256
      - TZ=Asia/Tokyo
    networks:
      - rust_todo_net
volumes:
  pgdata:

networks:
  rust_todo_net:
