version: "3.8"

services:
  rust:
    container_name: rust_todo
    env_file:
      - .env
    build: .
    tty: true
    volumes:
      - .:/workspace
    ports:
      - ${PORT}:${PORT}
    networks:
      - rust_todo_net
  db:
    container_name: todo_db
    image: postgres:latest
    volumes: 
      - pgdata:/var/lib/postgresql/data
      - ./db_config/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256 --auth-local=scram-sha-256
      - TZ=Asia/Tokyo
    restart: always
    networks:
      - rust_todo_net
volumes:
  pgdata:

networks:
  rust_todo_net:
