[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.db_create]
command = "sqlx"
args = ["db","create"]

[tasks.migrate]
command = "sqlx"
args = ["migrate","run"]
dependencies = ["db_create"]
cwd = "/workspace"

[tasks.format]
command = "cargo"
args = ["+nightly","fmt"]

[tasks.back]
command = "cargo"
args = ["watch","-x","run","-C","backend"]
dependencies = ["format"]
cwd = "/workspace"

[tasks.back_test]
command = "cargo"
args = ["test","--bin","rust-todo-backend"]
dependencies = ["format"]

[tasks.back_test_alone]
command = "cargo"
args = ["test","--no-default-features","--bin","rust-todo-backend"]
dependencies = ["format"]

[tasks.echo]
command = "echo"
args = ["${CARGO_MAKE_WORKING_DIRECTORY}"]

[tasks.trunk-clean]
command = "trunk"
args = ["clean"]

[tasks.clean]
dependencies = ["trunk-clean"]
command = "cargo"
args = ["clean"]

