name: Dockerfile lint

on:
  push:
    branch: master
    paths: ['Dockerfile','.github/workflows/dockerfile-format.yml']

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Install Hadolint
      run: |
        wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
        chmod +x /usr/local/bin/hadolint

    - name: Lint Dockerfile
      run: |
        hadolint Dockerfile